# Generated by Django 4.2.8 on 2024-09-14 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photosgallerynew',
            options={'verbose_name_plural': 'Galleries'},
        ),
    ]
