# Generated by Django 4.2.8 on 2024-09-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
