# Generated by Django 4.2.8 on 2024-09-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0002_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='photos/')),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
