# Generated by Django 4.2.8 on 2024-08-31 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='reason',
        ),
    ]
