# Generated by Django 4.2.8 on 2024-01-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subscribed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter subscribers',
                'ordering': ['created'],
            },
        ),
    ]
