# Generated by Django 4.2.8 on 2024-09-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subscribedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
