# Generated by Django 4.2.8 on 2024-09-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newsletter_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='other',
        ),
    ]
