# Generated by Django 4.2.8 on 2024-09-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_newsletter_other'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscribedusers',
            table='SubscribedUserss',
        ),
    ]
