# Generated by Django 4.2.8 on 2024-09-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_subscribedusers_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscribedusers',
            table='SubscribedUsers',
        ),
    ]
