# Generated by Django 4.2.8 on 2024-07-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_pricemax_product_pricemin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='priceMax',
        ),
        migrations.RemoveField(
            model_name='product',
            name='priceMin',
        ),
    ]
