# Generated by Django 4.2.8 on 2024-07-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_pricemax_remove_product_pricemin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceMax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='priceMin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
